
const data = {
    "Helios": {
        "link": "https://www.mines.edu/shared-facilities/project/fei-helios-nanolab-600i-fib-sem/",
        "phase-solid": true,
        "solid_form-crystalline": true,
        "solid_form-amorphous": true,
        "solid_form-thin_film": true,
        "solid_form-powder": true,
        "solid_props-phase": true,
        "solid_props-crystallographic_texture": true,
        "spatial_res-mm": true,
        "spatial_res-um": true,
        "spatial_res-nm": true,
        "dimensionality-1d": true,
        "dimensionality-2d": true,
        "dimensionality-3d": true,
        "comp_sensitivity-a_few_at_%": true,
        "temp-room": true,
        "atmosphere-vacuum": true,
    },
    "Tescan": {
        "link": "https://www.mines.edu/shared-facilities/project/tescan-s8252g-raman-sem-fib/",
        "phase-solid": true,
        "solid_form-crystalline": true,
        "solid_form-amorphous": true,
        "solid_form-thin_film": true,
        "solid_form-powder": true,
        "solid_props-phase": true,
        "solid_props-crystallographic_texture": true,
        "solid_props-chemical_bonding": true,
        "spatial_res-mm": true,
        "spatial_res-um": true,
        "spatial_res-nm": true,
        "dimensionality-1d": true,
        "dimensionality-2d": true,
        "dimensionality-3d": true,
        "comp_sensitivity-a_few_at_%": true,
        "temp-room": true,
        "temp-heated": true,
        "mech_testing-tension": true,
        "mech_testing-compression": true,
        "atmosphere-vacuum": true,
        "atmosphere-other": true,
    },
    "JEOL": {
        "link": "https://www.mines.edu/shared-facilities/project/jeol-jsf-7000f-field-emission-sem/",
        "phase-solid": true,
        "solid_form-crystalline": true,
        "solid_form-amorphous": true,
        "solid_form-thin_film": true,
        "solid_form-powder": true,
        "solid_props-phase": true,
        "solid_props-crystallographic_texture": true,
        "spatial_res-mm": true,
        "spatial_res-um": true,
        "spatial_res-nm": true,
        "dimensionality-1d": true,
        "dimensionality-2d": true,
        "comp_sensitivity-a_few_at_%": true,
        "temp-room": true,
        "atmosphere-vacuum": true,
    },
    "Quanta": {
        "link": "https://www.mines.edu/shared-facilities/project/fei-quanta-600i-environmental-sem/",
        "phase-solid": true,
        "solid_form-crystalline": true,
        "solid_form-amorphous": true,
        "solid_form-thin_film": true,
        "solid_form-powder": true,
        "spatial_res-mm": true,
        "spatial_res-um": true,
        "dimensionality-1d": true,
        "dimensionality-2d": true,
        "comp_sensitivity-a_few_at_%": true,
        "temp-room": true,
        "atmosphere-vacuum": true,
        "atmosphere-other": true,
    },
    "Phenom": {
        "link": "https://www.mines.edu/shared-facilities/project/phenom/",
        "phase-solid": true,
        "solid_form-crystalline": true,
        "solid_form-amorphous": true,
        "solid_form-thin_film": true,
        "solid_form-powder": true,
        "spatial_res-mm": true,
        "spatial_res-um": true,
        "dimensionality-1d": true,
        "dimensionality-2d": true,
        "temp-room": true,
        "atmosphere-vacuum": true,
        "atmosphere-other": true,
    },
    "TOF-SIMS": {
        "link": "https://www.mines.edu/shared-facilities/project/iontof-tof-sims-v/",
        "phase-solid": true,
        "solid_form-crystalline": true,
        "solid_form-amorphous": true,
        "solid_form-thin_film": true,
        "solid_form-powder": true,
        "spatial_res-mm": true,
        "spatial_res-um": true,
        "spatial_res-nm": true,
        "dimensionality-1d": true,
        "dimensionality-2d": true,
        "dimensionality-3d": true,
        "comp_sensitivity-a_few_at_%": true,
        "comp_sensitivity-ppm": true,
        "temp-room": true,
        "atmosphere-vacuum": true,
        "atmosphere-other": true,
    },
    "LEAP": {
        "link": "https://www.mines.edu/shared-facilities/project/atomprobe/",
        "phase-solid": true,
        "solid_form-crystalline": true,
        "solid_form-amorphous": true,
        "solid_form-thin_film": true,
        "solid_form-powder": true,
        "spatial_res-um": true,
        "spatial_res-nm": true,
        "dimensionality-1d": true,
        "dimensionality-2d": true,
        "dimensionality-3d": true,
        "comp_sensitivity-a_few_at_%": true,
        "comp_sensitivity-ppm": true,
        "temp-room": true,
        "temp-cooled": true,
        "atmosphere-vacuum": true,
        "atmosphere-other": true,
    },
    "SCIEX 5500": {
        "link": "https://www.mines.edu/shared-facilities/project/sciex-5500-triple-quad/",
        "phase-liquid": true,
        "comp_sensitivity-a_few_at_%": true,
        "comp_sensitivity-ppm": true,
        "temp-room": true,
        "atmosphere-ambient": true,
    },
    "SCIEX X500R": {
        "link": "https://www.mines.edu/shared-facilities/project/sciex-x500r-qtof/",
        "phase-liquid": true,
        "comp_sensitivity-a_few_at_%": true,
        "comp_sensitivity-ppm": true,
        "temp-room": true,
        "atmosphere-ambient": true,
    },
    "OrbiTrap Exploris": {
        "link": "https://www.mines.edu/shared-facilities/project/orbitrap/",
        "phase-liquid": true,
        "comp_sensitivity-a_few_at_%": true,
        "comp_sensitivity-ppm": true,
        "temp-room": true,
        "atmosphere-ambient": true,
    },
    "FTIR": {
        "link": "https://www.mines.edu/shared-facilities/project/ftir/",
        "phase-solid": true,
        "phase-liquid": true,
        "solid_form-crystalline": true,
        "solid_form-amorphous": true,
        "solid_form-thin_film": true,
        "solid_form-powder": true,
        "solid_props-chemical_bonding": true,
        "spatial_res-mm": true,
        "dimensionality-1d": true,
        "comp_sensitivity-a_few_at_%": true,
        "temp-room": true,
        "atmosphere-ambient": true,
    },
    "UV-Vis": {
        "link": "https://www.mines.edu/shared-facilities/project/uvis/",
        "phase-solid": true,
        "solid_form-crystalline": true,
        "solid_form-amorphous": true,
        "solid_form-thin_film": true,
        "solid_form-powder": true,
        "solid_props-chemical_bonding": true,
        "spatial_res-mm": true,
        "dimensionality-1d": true,
        "temp-room": true,
        "atmosphere-ambient": true,
    },
    "Ellipsometer": {
        "link": "https://www.mines.edu/shared-facilities/project/m2000/",
        "phase-solid": true,
        "solid_form-crystalline": true,
        "solid_form-amorphous": true,
        "solid_form-thin_film": true,
        "solid_props-phase": true,
        "solid_props-strain": true,
        "spatial_res-mm": true,
        "dimensionality-1d": true,
        "temp-room": true,
        "atmosphere-ambient": true,
    },
    "SPM (Asylum MFP-3D)": {
        "link": "",     // TODO: get this link!!! <==========================================
        "phase-solid": true,
        "phase-liquid": true,
        "solid_form-crystalline": true,
        "solid_form-amorphous": true,
        "solid_form-thin_film": true,
        "solid_form-powder": true,
        "solid_props-phase": true,
        "solid_props-strain": true,
        "spatial_res-um": true,
        "spatial_res-nm": true,
        "dimensionality-1d": true,
        "dimensionality-2d": true,
        "temp-room": true,
        "temp-heated": true,
        "temp-cooled": true,
        "mech_testing-tension": true,
        "mech_testing-compression": true,
        "atmosphere-ambient": true,
        "atmosphere-other": true,
    },
    "AFM (Digital Instruments)": {
        "link": "https://www.mines.edu/shared-facilities/project/digitalafm/",
        "phase-solid": true,
        "solid_form-crystalline": true,
        "solid_form-amorphous": true,
        "solid_form-thin_film": true,
        "solid_form-powder": true,
        "solid_props-phase": true,
        "solid_props-strain": true,
        "spatial_res-um": true,
        "spatial_res-nm": true,
        "dimensionality-1d": true,
        "dimensionality-2d": true,
        "temp-room": true,
        "atmosphere-ambient": true,
    },
    "Profilometer": {
        "link": "https://www.mines.edu/shared-facilities/project/profilometer/",
        "phase-solid": true,
        "solid_form-crystalline": true,
        "solid_form-amorphous": true,
        "solid_form-thin_film": true,
        "solid_form-powder": true,
        "spatial_res-mm": true,
        "spatial_res-um": true,
        "dimensionality-1d": true,
        "dimensionality-2d": true,
        "temp-room": true,
        "atmosphere-ambient": true,
    },
    "Keyence": {
        "link": "https://www.mines.edu/shared-facilities/project/keyence/",
        "phase-solid": true,
        "phase-liquid": true,
        "solid_form-crystalline": true,
        "solid_form-amorphous": true,
        "solid_form-thin_film": true,
        "solid_form-powder": true,
        "spatial_res-mm": true,
        "spatial_res-um": true,
        "dimensionality-1d": true,
        "dimensionality-2d": true,
        "dimensionality-3d": true,
        "temp-room": true,
        "atmosphere-ambient": true,
    },
    "WITec Confocal": {
        "link": "https://www.mines.edu/shared-facilities/project/witec-laser-confocal-raman-microscope/",
        "phase-solid": true,
        "phase-liquid": true,
        "solid_form-crystalline": true,
        "solid_form-amorphous": true,
        "solid_form-thin_film": true,
        "solid_form-powder": true,
        "solid_props-strain": true,
        "solid_props-chemical_bonding": true,
        "spatial_res-mm": true,
        "spatial_res-um": true,
        "dimensionality-1d": true,
        "dimensionality-2d": true,
        "dimensionality-3d": true,
        "temp-room": true,
        "atmosphere-ambient": true,
    },
    "DR-6000 Hach": {
        "link": "https://www.mines.edu/shared-facilities/project/wqa/",
        "phase-liquid": true,
        "comp_sensitivity-a_few_at_%": true,
        "comp_sensitivity-ppm": true,
        "temp-room": true,
        "atmosphere-ambient": true,
    },
    "Shimadzu TOC-L": {
        "link": "https://www.mines.edu/shared-facilities/project/toc/",
        "phase-liquid": true,
        "comp_sensitivity-a_few_at_%": true,
        "comp_sensitivity-ppm": true,
        "temp-room": true,
        "atmosphere-ambient": true,
    },
    "Thermo Dionex ICS-900": {
        "link": "https://www.mines.edu/shared-facilities/project/ic/",
        "phase-liquid": true,
        "comp_sensitivity-a_few_at_%": true,
        "comp_sensitivity-ppm": true,
        "temp-room": true,
        "atmosphere-ambient": true,
    },
    "Panalytical Empyrean": {
        "link": "https://www.mines.edu/shared-facilities/project/malvern-panalytical-empyrean-x-ray-diffractometer/",
        "phase-solid": true,
        "solid_form-crystalline": true,
        "solid_form-amorphous": true,
        "solid_form-thin_film": true,
        "solid_form-powder": true,
        "solid_props-phase": true,
        "solid_props-crystallographic_texture": true,
        "solid_props-strain": true,
        "spatial_res-mm": true,
        "dimensionality-1d": true,
        "dimensionality-2d": true,
        "temp-room": true,
        "temp-heated": true,
        "temp-cooled": true,
        "atmosphere-ambient": true,
        "atmosphere-other": true,
    },
    "Panalytical X'Pert Pro": {
        "link": "https://www.mines.edu/shared-facilities/project/panalytical-pw3040-x-ray-diffractometer/",
        "phase-solid": true,
        "solid_form-crystalline": true,
        "solid_form-amorphous": true,
        "solid_form-thin_film": true,
        "solid_form-powder": true,
        "solid_props-phase": true,
        "solid_props-crystallographic_texture": true,
        "spatial_res-mm": true,
        "dimensionality-1d": true,
        "temp-room": true,
        "atmosphere-ambient": true,
    },
    "Zeiss Versa XCT": {
        "link": "https://www.mines.edu/shared-facilities/project/zeiss-versa-x-ray-microscope/",
        "phase-solid": true,
        "solid_form-crystalline": true,
        "solid_form-amorphous": true,
        "solid_props-phase": true,
        "spatial_res-mm": true,
        "spatial_res-um": true,
        "dimensionality-1d": true,
        "dimensionality-2d": true,
        "dimensionality-3d": true,
        "temp-room": true,
        "mech_testing-tension": true,
        "mech_testing-compression": true,
        "atmosphere-ambient": true,
    },
    "Extensometer": {
        "link": "",     // TODO: get this link!!! <==========================================
        "phase-solid": true,
        "solid_form-crystalline": true,
        "solid_form-amorphous": true,
        "solid_props-strain": true,
        "spatial_res-mm": true,
        "spatial_res-um": true,
        "dimensionality-1d": true,
        "temp-room": true,
        "temp-heated": true,
        "temp-cooled": true,
        "mech_testing-tension": true,
        "mech_testing-compression": true,
        "force_ranges-n": true,
        "force_ranges-kn": true,
        "atmosphere-ambient": true,
        "atmosphere-vacuum": true,
        "atmosphere-other": true,
    },
    "Digital Image Correlation": {
        "link": "",     // TODO: get this link!!! <==========================================
        "phase-solid": true,
        "solid_form-crystalline": true,
        "solid_form-amorphous": true,
        "solid_form-thin_film": true,
        "solid_props-strain": true,
        "spatial_res-mm": true,
        "spatial_res-um": true,
        "dimensionality-1d": true,
        "dimensionality-2d": true,
        "dimensionality-3d": true,
        "temp-room": true,
        "temp-heated": true,
        "temp-cooled": true,
        "mech_testing-tension": true,
        "mech_testing-compression": true,
        "mech_testing-bending": true,
        "mech_testing-torsion": true,
        "mech_testing-static": true,
        "force_ranges-n": true,
        "force_ranges-kn": true,
        "atmosphere-ambient": true,
        "atmosphere-vacuum": true,
        "atmosphere-other": true,
    },
    "MTS Environmental Chamber": {
        "link": "",     // TODO: get this link!!! <==========================================
        "phase-solid": true,
        "solid_form-crystalline": true,
        "solid_form-amorphous": true,
        "temp-heated": true,
        "temp-cooled": true,
        "mech_testing-tension": true,
        "mech_testing-compression": true,
        "mech_testing-bending": true,
        "mech_testing-static": true,
        "mech_testing-fatigue": true,
        "force_ranges-kn": true,
        "atmosphere-ambient": true,
    },
    "Induction Furnace": {
        "link": "",     // TODO: get this link!!! <==========================================
        "phase-solid": true,
        "solid_form-crystalline": true,
        "solid_form-amorphous": true,
        "temp-heated": true,
        "mech_testing-tension": true,
        "mech_testing-compression": true,
        "mech_testing-bending": true,
        "mech_testing-static": true,
        "mech_testing-fatigue": true,
        "force_ranges-n": true,
        "force_ranges-kn": true,
        "atmosphere-ambient": true,
    }, 
    "Gleeble": {
        "link": "",     // TODO: get this link!!! <==========================================
        "phase-solid": true,
        "solid_form-crystalline": true,
        "solid_form-amorphous": true,
        "solid_props-strain": true,
        "spatial_res-mm": true,
        "spatial_res-um": true,
        "dimensionality-1d": true,
        "temp-room": true,
        "temp-heated": true,
        "mech_testing-tension": true,
        "mech_testing-compression": true,
        "mech_testing-torsion": true,
        "mech_testing-static": true,
        "force_ranges-kn": true,
        "atmosphere-ambient": true,
        "atmosphere-vacuum": true,
        "atmosphere-other": true,
    },
    "MARK-10 ESM1500": {
        "link": "",     // TODO: get this link!!! <==========================================
        "phase-solid": true,
        "solid_form-crystalline": true,
        "solid_form-amorphous": true,
        "solid_form-thin_film": true,
        "solid_props-strain": true,
        "spatial_res-mm": true,
        "spatial_res-um": true,
        "dimensionality-1d": true,
        "temp-room": true,
        "mech_testing-tension": true,
        "mech_testing-compression": true,
        "mech_testing-bending": true,
        "mech_testing-static": true,
        "force_ranges-n": true,
        "force_ranges-kn": true,
        "atmosphere-ambient": true,
    },
    "MTS Alliance RT/100": {
        "link": "",     // TODO: get this link!!! <==========================================
        "phase-solid": true,
        "solid_form-crystalline": true,
        "solid_form-amorphous": true,
        "solid_props-strain": true,
        "spatial_res-mm": true,
        "spatial_res-um": true,
        "dimensionality-1d": true,
        "temp-room": true,
        "mech_testing-tension": true,
        "mech_testing-compression": true,
        "mech_testing-bending": true,
        "mech_testing-static": true,
        "force_ranges-n": true,
        "force_ranges-kn": true,
        "atmosphere-ambient": true,
    },
    "Instru-Met ReNew 1125": {
        "link": "",     // TODO: get this link!!! <==========================================
        "phase-solid": true,
        "solid_form-crystalline": true,
        "solid_form-amorphous": true,
        "solid_props-strain": true,
        "spatial_res-mm": true,
        "spatial_res-um": true,
        "dimensionality-1d": true,
        "temp-room": true,
        "temp-heated": true,
        "mech_testing-tension": true,
        "mech_testing-compression": true,
        "mech_testing-torsion": true,
        "mech_testing-static": true,
        "force_ranges-n": true,
        "force_ranges-kn": true,
        "atmosphere-ambient": true,
    }, 
    "SF-1-U": {
        "link": "",     // TODO: get this link!!! <==========================================
        "phase-solid": true,
        "solid_form-crystalline": true,
        "solid_form-amorphous": true,
        "dimensionality-1d": true,
        "mech_testing-bending": true,
        "mech_testing-torsion": true,
        "mech_testing-fatigue": true,
        "force_ranges-n": true,
        "force_ranges-kn": true,
        "atmosphere-ambient": true,
    },
    "Rotating Bending Fatigue": {
        "link": "",     // TODO: get this link!!! <==========================================
        "phase-solid": true,
        "solid_form-crystalline": true,
        "solid_form-amorphous": true,
        "dimensionality-1d": true,
        "mech_testing-bending": true,
        "mech_testing-fatigue": true,
        "force_ranges-n": true,
        "force_ranges-kn": true,
        "atmosphere-ambient": true,
    },
    "MTS Landmark 370.10": {
        "link": "",     // TODO: get this link!!! <==========================================
        "phase-solid": true,
        "solid_form-crystalline": true,
        "solid_form-amorphous": true,
        "solid_props-strain": true,
        "spatial_res-mm": true,
        "spatial_res-um": true,
        "dimensionality-1d": true,
        "temp-room": true,
        "temp-heated": true,
        "mech_testing-tension": true,
        "mech_testing-compression": true,
        "mech_testing-bending": true,
        "mech_testing-static": true,
        "mech_testing-fatigue": true,
        "force_ranges-n": true,
        "force_ranges-kn": true,
        "atmosphere-ambient": true,
    },
    "MTS Landmark 370.25": {
        "link": "",     // TODO: get this link!!! <==========================================
        "phase-solid": true,
        "solid_form-crystalline": true,
        "solid_form-amorphous": true,
        "solid_props-strain": true,
        "spatial_res-mm": true,
        "spatial_res-um": true,
        "dimensionality-1d": true,
        "temp-room": true,
        "temp-heated": true,
        "temp-cooled": true,
        "mech_testing-tension": true,
        "mech_testing-compression": true,
        "mech_testing-bending": true,
        "mech_testing-static": true,
        "mech_testing-fatigue": true,
        "force_ranges-kn": true,
        "atmosphere-ambient": true,
    },
    "MTS 312.21 Top Actuator": {
        "link": "",     // TODO: get this link!!! <==========================================
        "phase-solid": true,
        "solid_form-crystalline": true,
        "solid_form-amorphous": true,
        "solid_props-strain": true,
        "spatial_res-mm": true,
        "spatial_res-um": true,
        "dimensionality-1d": true,
        "temp-room": true,
        "mech_testing-tension": true,
        "mech_testing-compression": true,
        "mech_testing-bending": true,
        "mech_testing-static": true,
        "mech_testing-fatigue": true,
        "force_ranges-n": true,
        "force_ranges-kn": true,
        "atmosphere-ambient": true,
    },
    "MTS 312.21 Hydraulic Grips": {
        "link": "",     // TODO: get this link!!! <==========================================
        "phase-solid": true,
        "solid_form-crystalline": true,
        "solid_form-amorphous": true,
        "solid_props-strain": true,
        "spatial_res-mm": true,
        "spatial_res-um": true,
        "dimensionality-1d": true,
        "temp-room": true,
        "mech_testing-tension": true,
        "mech_testing-compression": true,
        "mech_testing-bending": true,
        "mech_testing-static": true,
        "mech_testing-fatigue": true,
        "force_ranges-n": true,
        "force_ranges-kn": true,
        "atmosphere-ambient": true,
    },
    "MTS 312.21 BUT": {
        "link": "",     // TODO: get this link!!! <==========================================
        "phase-solid": true,
        "solid_form-crystalline": true,
        "solid_form-amorphous": true,
        "solid_props-strain": true,
        "spatial_res-mm": true,
        "spatial_res-um": true,
        "dimensionality-1d": true,
        "temp-room": true,
        "mech_testing-tension": true,
        "mech_testing-compression": true,
        "mech_testing-bending": true,
        "mech_testing-static": true,
        "mech_testing-fatigue": true,
        "force_ranges-n": true,
        "force_ranges-kn": true,
        "atmosphere-ambient": true,
    },
    "MTS 312.41": {
        "link": "",     // TODO: get this link!!! <==========================================
        "phase-solid": true,
        "solid_form-crystalline": true,
        "solid_form-amorphous": true,
        "solid_props-strain": true,
        "spatial_res-mm": true,
        "spatial_res-um": true,
        "dimensionality-1d": true,
        "temp-room": true,
        "mech_testing-tension": true,
        "mech_testing-compression": true,
        "mech_testing-bending": true,
        "mech_testing-static": true,
        "mech_testing-fatigue": true,
        "force_ranges-kn": true,
        "force_ranges-gt250kn": true,
        "atmosphere-ambient": true,
    },
}